<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0b1220,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,34px);
    border-left:clamp(5px,0.8vw,8px) solid #3b82f6;
    border-radius:14px;
    box-shadow:0 8px 25px rgba(0,0,0,0.25);
    margin:0 0 30px 0;
    overflow-wrap:break-word;
    word-wrap:break-word;
">

<h1 style="
    margin:0;
    font-size:clamp(26px,4vw,38px);
    line-height:1.15;
    color:#ffffff;
    font-weight:700;
">
🌎 Calidad del Aire en Santiago
</h1>

<p style="
    margin-top:10px;
    font-size:clamp(15px,1.8vw,18px);
    line-height:1.5;
    color:#60a5fa;
    font-weight:600;
">
Proyecto Integrador F3 · Magíster en Ciencia de Datos e Inteligencia Artificial (MCDI500) · Grupo 3
</p>

<hr style="border:1px solid #334155;margin:20px 0;">

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
">
La contaminación atmosférica constituye uno de los principales desafíos ambientales y sanitarios de las grandes ciudades modernas. En la Región Metropolitana de Santiago, la presencia recurrente de episodios críticos asociados al material particulado fino (<strong>PM2.5</strong>) y respirable (<strong>PM10</strong>) impacta directamente la salud de la población, la calidad de vida urbana y la toma de decisiones de organismos públicos encargados de la gestión ambiental.
</p>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
">
Este proyecto aplica técnicas de <strong>Ciencia de Datos</strong> para analizar información proveniente de la Red Nacional de Monitoreo de Calidad del Aire (<strong>SINCA</strong>), integrando procesos de adquisición, limpieza, transformación, validación y exploración de datos ambientales con el propósito de identificar patrones, relaciones y comportamientos relevantes entre las condiciones meteorológicas y los niveles de contaminación observados en Santiago.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#172554;
    border-left:5px solid #60a5fa;
    padding:clamp(14px,2vw,18px);
    margin-top:20px;
    border-radius:8px;
">

<h3 style="
    margin-top:0;
    color:#bfdbfe;
    font-size:clamp(17px,2vw,21px);
">
🔍 Pregunta de Investigación
</h3>

<p style="
    font-size:clamp(15px,1.7vw,17px);
    line-height:1.75;
    color:#ffffff;
    margin-bottom:0;
">
<strong>
¿Qué variables meteorológicas presentan una relación significativa con la ocurrencia de episodios críticos de contaminación atmosférica por material particulado en Santiago y cómo contribuyen a explicar su comportamiento temporal?
</strong>
</p>

</div>

<h3 style="
    margin-top:25px;
    color:#93c5fd;
    font-size:clamp(17px,2vw,21px);
">
🎯 Objetivo del Análisis
</h3>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
">
Identificar patrones de contaminación atmosférica mediante análisis exploratorio y técnicas de procesamiento de datos, evaluando la influencia de variables meteorológicas sobre los contaminantes monitoreados y generando evidencia objetiva que permita comprender mejor la dinámica ambiental de la ciudad.
</p>

<h3 style="
    margin-top:25px;
    color:#93c5fd;
    font-size:clamp(17px,2vw,21px);
">
⚙️ Metodología Aplicada
</h3>

<ul style="
    font-size:clamp(14px,1.45vw,15.5px);
    line-height:1.8;
    color:#dbeafe;
    padding-left:clamp(20px,3vw,32px);
">
<li>Obtención y consolidación de datos oficiales SINCA.</li>
<li>Evaluación de calidad e integridad de los datos.</li>
<li>Tratamiento de valores faltantes mediante imputación robusta.</li>
<li>Transformación y normalización de variables.</li>
<li>Análisis exploratorio de datos (EDA).</li>
<li>Visualización de tendencias, distribuciones y correlaciones.</li>
<li>Implementación y evaluación de algoritmos desarrollados para el proyecto.</li>
<li>Validación de resultados y documentación reproducible.</li>
</ul>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:25px;
    padding:clamp(14px,2vw,18px);
    background:#0f172a;
    border:1px solid #334155;
    border-radius:8px;
">

<p style="
    margin:0;
    font-size:clamp(14px,1.45vw,15.5px);
    line-height:1.8;
    color:#cbd5e1;
    text-align:justify;
">
📘 <strong>Reproducibilidad y Trazabilidad:</strong>
Todo el proceso analítico se encuentra documentado mediante notebooks Jupyter, código Python versionado en Git/GitHub y artefactos de soporte asociados al proyecto, permitiendo la reproducción íntegra de los resultados y garantizando transparencia metodológica, trazabilidad técnica y colaboración efectiva entre los integrantes del equipo.
</p>

</div>

</div>

<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0f172a,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,30px);
    border-left:clamp(5px,0.8vw,7px) solid #3b82f6;
    border-radius:12px;
    box-shadow:0 8px 20px rgba(0,0,0,0.20);
    margin-bottom:24px;
    overflow-wrap:break-word;
    word-wrap:break-word;
">

<h2 style="
    margin-top:0;
    margin-bottom:16px;
    color:#ffffff;
    font-size:clamp(24px,3vw,32px);
    font-weight:700;
">
1. Configuración del Entorno Analítico
</h2>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
    margin-bottom:16px;
">
Esta sección establece la base técnica del notebook para el proyecto <strong>F3 – Calidad del Aire en Santiago</strong>. Su objetivo es preparar un entorno de análisis reproducible, consistente y auditable, asegurando que los procesos de carga, limpieza, transformación, exploración y visualización de datos se ejecuten bajo criterios metodológicos controlados y verificables.
</p>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
">
El entorno utiliza bibliotecas estándar del ecosistema Python para Ciencia de Datos: <strong>Pandas</strong> para manipulación tabular, <strong>NumPy</strong> para procesamiento numérico, <strong>Matplotlib</strong> y <strong>Seaborn</strong> para visualización analítica, además de <strong>OS</strong> y <strong>Pathlib</strong> para la gestión del sistema de archivos y la trazabilidad de los recursos utilizados durante la ejecución del proyecto.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#172554;
    border-left:5px solid #60a5fa;
    padding:clamp(14px,2vw,18px);
    border-radius:8px;
    margin-top:20px;
">

<h3 style="
    margin-top:0;
    margin-bottom:10px;
    color:#bfdbfe;
    font-size:clamp(16px,2vw,20px);
">
🎯 Resultado Esperado
</h3>

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#ffffff;
    text-align:justify;
">
Disponer de un entorno técnico completamente validado, con versiones de librerías registradas, parámetros gráficos homogéneos, configuraciones reproducibles y controles básicos de calidad que garanticen consistencia metodológica, trazabilidad de ejecución y confiabilidad de los resultados obtenidos durante el análisis.
</p>

</div>

</div>

In [ ]:
# =============================================================================
# 1. CONFIGURACIÓN DEL ENTORNO ANALÍTICO
# Proyecto F3: Calidad del Aire en Santiago
# MCDI500 - Ciencia de Datos e Inteligencia Artificial
# =============================================================================

import sys
import os
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------------------------------------------------------
# Configuración general de Pandas
# -----------------------------------------------------------------------------

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.3f}".format)

# -----------------------------------------------------------------------------
# Paleta visual profesional para notebook en tema oscuro
# -----------------------------------------------------------------------------

COL = {
    "fondo": "#0d1117",
    "panel": "#111827",
    "texto": "#e6edf3",
    "subtexto": "#8b949e",
    "grid": "#21262d",
    "primario": "#58a6ff",
    "alerta": "#f85149",
    "ok": "#3fb950",
    "warning": "#d29922",
}

plt.rcParams.update({
    "figure.facecolor": COL["fondo"],
    "savefig.facecolor": COL["fondo"],
    "axes.facecolor": COL["fondo"],
    "axes.edgecolor": COL["grid"],
    "axes.labelcolor": COL["texto"],
    "axes.titlecolor": COL["texto"],
    "xtick.color": COL["subtexto"],
    "ytick.color": COL["subtexto"],
    "grid.color": COL["grid"],
    "grid.alpha": 0.6,
    "axes.grid": True,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "font.family": "DejaVu Sans",
    "font.size": 11,
    "axes.titlesize": 15,
    "axes.titleweight": "bold",
    "figure.dpi": 120,
})

sns.set_theme(style="darkgrid", context="notebook")

# -----------------------------------------------------------------------------
# Validación robusta del entorno
# -----------------------------------------------------------------------------

required_libraries = {
    "Python": sys.version.split()[0],
    "Pandas": pd.__version__,
    "NumPy": np.__version__,
    "Matplotlib": matplotlib.__version__,
    "Seaborn": sns.__version__,
    "OS": f"{os.name} / {sys.platform}",
}

project_checks = {
    "Directorio actual": Path.cwd(),
    "Notebook ejecutable": True,
    "Configuración Pandas": pd.get_option("display.max_columns") is None,
    "Tema visual Matplotlib": plt.rcParams["axes.facecolor"] == COL["fondo"],
    "Tema visual Seaborn": True,
}

print("╔══════════════════════════════════════════════════════════════╗")
print("║        VALIDACIÓN DEL ENTORNO ANALÍTICO - PROYECTO F3        ║")
print("╚══════════════════════════════════════════════════════════════╝")
print(f"Fecha de validación : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Proyecto            : F3 - Calidad del Aire en Santiago")
print(f"Ruta de trabajo     : {Path.cwd()}")
print("")

print("Versiones del entorno:")
for name, version in required_libraries.items():
    print(f"✓ {name:<12}: {version}")

print("")
print("Controles técnicos:")
for check, value in project_checks.items():
    status = "OK" if value else "REVISAR"
    symbol = "✓" if value else "⚠"
    print(f"{symbol} {check:<28}: {status}")

print("")
print("Resultado:")
print("✓ Entorno analítico configurado correctamente.")
print("✓ Librerías principales cargadas y versionadas.")
print("✓ Parámetros visuales estandarizados.")
print("✓ Notebook preparado para análisis reproducible y trazable.")

<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0f172a,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,30px);
    border-left:clamp(5px,0.8vw,7px) solid #06b6d4;
    border-radius:12px;
    box-shadow:0 8px 20px rgba(0,0,0,0.20);
    margin-bottom:24px;
    overflow-wrap:break-word;
    word-wrap:break-word;
">

<h2 style="
    margin-top:0;
    margin-bottom:16px;
    color:#ffffff;
    font-size:clamp(24px,3vw,32px);
    font-weight:700;
">
2. Inspección y Validación del Archivo Fuente
</h2>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
    margin-bottom:16px;
">
Antes de incorporar los datos al flujo analítico, se realiza una inspección preliminar del archivo fuente con el propósito de verificar su estructura, codificación, integridad y formato de almacenamiento. Esta práctica constituye una etapa esencial dentro de cualquier proyecto de Ciencia de Datos, ya que permite detectar tempranamente inconsistencias que podrían comprometer la calidad, confiabilidad y reproducibilidad de los resultados obtenidos en etapas posteriores.
</p>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#dbeafe;
    text-align:justify;
">
La validación inicial permite confirmar aspectos críticos tales como el delimitador utilizado, la codificación de caracteres, la presencia de encabezados, la estructura tabular y el formato numérico empleado por la fuente oficial. En el caso de los registros provenientes de la Red Nacional de Monitoreo de Calidad del Aire (<strong>SINCA</strong>), es habitual encontrar archivos CSV con separador punto y coma (<strong>;</strong>) y representación decimal basada en coma (<strong>,</strong>), características que deben ser consideradas explícitamente durante la carga para evitar errores de interpretación y pérdida de información.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#164e63;
    border-left:5px solid #22d3ee;
    padding:clamp(14px,2vw,18px);
    border-radius:8px;
    margin-top:20px;
">

<h3 style="
    margin-top:0;
    margin-bottom:10px;
    color:#cffafe;
    font-size:clamp(16px,2vw,20px);
">
🔎 Resultado Esperado
</h3>

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#ffffff;
    text-align:justify;
">
Validar que el archivo fuente posee una estructura consistente, íntegra y compatible con el proceso de carga, verificando la existencia del archivo, el formato de almacenamiento, la codificación utilizada y los parámetros necesarios para garantizar una incorporación correcta de los datos al entorno analítico sin alteraciones ni pérdidas de información.
</p>

</div>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:18px;
    padding:clamp(14px,2vw,18px);
    background:#082f49;
    border:1px solid #0ea5e9;
    border-radius:8px;
">

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#dbeafe;
    text-align:justify;
">
📘 <strong>Justificación Técnica:</strong>
La inspección temprana del archivo fuente reduce significativamente el riesgo de errores durante la carga de datos, facilita la identificación de problemas de codificación o delimitación y proporciona evidencia verificable de que la fuente utilizada cumple las condiciones mínimas necesarias para garantizar trazabilidad, reproducibilidad y calidad metodológica del análisis.
</p>

</div>

</div>

In [ ]:
# =============================================================================
# 2. INSPECCIÓN DEL ARCHIVO FUENTE
# Proyecto F3: Calidad del Aire en Santiago
# MCDI500 - Ciencia de Datos e Inteligencia Artificial
# =============================================================================

from pathlib import Path
import os
ruta = Path("../data/raw/sinca_santiago.csv")
print("╔══════════════════════════════════════════════════════════════╗")
print("║          VALIDACIÓN DEL ARCHIVO FUENTE (CSV)               ║")
print("╚══════════════════════════════════════════════════════════════╝")
# Verificar existencia
print(f"\nArchivo encontrado : {'✓ Sí' if ruta.exists() else '✗ No'}")
print(f"Ruta              : {ruta.resolve()}")

if ruta.exists():

    tamaño_mb = ruta.stat().st_size / (1024 * 1024)

    print(f"Tamaño            : {tamaño_mb:.2f} MB")
    print(f"Nombre            : {ruta.name}")

    print("\nPrimeras líneas del archivo:")
    print("-" * 80)

    with open(ruta, encoding="latin-1") as f:
        primeras_lineas = [f.readline().strip() for _ in range(5)]

    for i, linea in enumerate(primeras_lineas, start=1):
        print(f"Línea {i:02d}: {linea[:120]}")

    print("-" * 80)

    # Validaciones básicas
    encabezado = primeras_lineas[0]

    tiene_punto_coma = ";" in encabezado
    tiene_coma_decimal = any("," in l for l in primeras_lineas[1:])

    print("\nValidaciones:")
    print(f"✓ Separador ';' detectado     : {tiene_punto_coma}")
    print(f"✓ Coma decimal observada      : {tiene_coma_decimal}")
    print(f"✓ Codificación utilizada      : latin-1")

    print("\nResultado:")
    print("✓ Archivo válido para etapa de carga y procesamiento.")

else:
    print("\nERROR: archivo no encontrado.")

<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0f172a,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,30px);
    border-left:clamp(5px,0.8vw,7px) solid #10b981;
    border-radius:12px;
    box-shadow:0 8px 20px rgba(0,0,0,0.20);
    margin-bottom:24px;
    overflow-wrap:break-word;
    word-wrap:break-word;
">

<h2 style="
    margin-top:0;
    margin-bottom:16px;
    color:#ffffff;
    font-size:clamp(24px,3vw,32px);
    font-weight:700;
">
3. Carga, Normalización Inicial y Enriquecimiento de Datos
</h2>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#d1fae5;
    text-align:justify;
    margin-bottom:16px;
">
En esta etapa se realiza la incorporación controlada del conjunto de datos proveniente de la fuente oficial <strong>SINCA</strong>, considerando explícitamente las características técnicas del archivo de origen: separador punto y coma (<strong>;</strong>), representación decimal mediante coma (<strong>,</strong>) y codificación de caracteres <strong>latin-1</strong>. La definición explícita de estos parámetros permite minimizar errores de interpretación, preservar la integridad de los datos y garantizar una carga consistente dentro del entorno analítico.
</p>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#d1fae5;
    text-align:justify;
">
Posteriormente, se ejecuta un proceso de normalización inicial orientado a preparar el dataset para las etapas de exploración y modelamiento. Este procedimiento contempla la eliminación de registros vacíos, la estandarización de variables temporales, la homologación de categorías, la incorporación de unidades de medida en los encabezados y la clasificación semántica de las variables según su naturaleza analítica, facilitando su correcta interpretación y utilización durante el desarrollo del proyecto.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#064e3b;
    border-left:5px solid #34d399;
    padding:clamp(14px,2vw,18px);
    border-radius:8px;
    margin-top:20px;
">

<h3 style="
    margin-top:0;
    margin-bottom:10px;
    color:#a7f3d0;
    font-size:clamp(16px,2vw,20px);
">
📊 Resultado Esperado
</h3>

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#ffffff;
    text-align:justify;
">
Obtener un <strong>DataFrame estructurado, consistente y analíticamente preparado</strong>, con variables correctamente tipificadas, fechas normalizadas, categorías homologadas, unidades de medida explícitas y metadatos mínimos necesarios para garantizar interpretabilidad, trazabilidad y calidad técnica durante las siguientes fases del análisis.
</p>

</div>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:18px;
    padding:clamp(14px,2vw,18px);
    background:#052e16;
    border:1px solid #22c55e;
    border-radius:8px;
">

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#d1fae5;
    text-align:justify;
">
📘 <strong>Justificación Técnica:</strong>
La normalización temprana del conjunto de datos constituye una práctica fundamental en proyectos de Ciencia de Datos, ya que reduce inconsistencias estructurales, mejora la calidad de los datos disponibles para el análisis exploratorio y facilita la construcción posterior de modelos analíticos. La incorporación explícita de unidades físicas y la clasificación semántica de las variables contribuyen además a una interpretación más rigurosa de los fenómenos ambientales estudiados.
</p>

</div>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:18px;
    padding:clamp(14px,2vw,18px);
    background:#0f172a;
    border:1px solid #334155;
    border-radius:8px;
">

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#cbd5e1;
    text-align:justify;
">
🔬 <strong>Controles de Calidad Aplicados:</strong>
Verificación de existencia del archivo, validación del formato de origen, control de registros vacíos, conversión robusta de variables temporales, detección de fechas inválidas, homologación de categorías, enriquecimiento mediante unidades de medida y validación estructural del conjunto de datos previo al análisis exploratorio.
</p>

</div>

</div>

In [10]:

# =============================================================================
# 3. CARGA, NORMALIZACIÓN INICIAL Y ENRIQUECIMIENTO DEL DATASET
# Proyecto F3: Calidad del Aire en Santiago
# Fuente: SINCA
# =============================================================================

from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np

# -----------------------------------------------------------------------------
# 1) Configuración del archivo fuente
# -----------------------------------------------------------------------------

ruta = Path("../data/raw/sinca_santiago.csv")

#print("╔════════════════════════════════════════════════════════════════════╗")
#print("║        CARGA, NORMALIZACIÓN Y ENRIQUECIMIENTO DEL DATASET         ║")
#print("╚════════════════════════════════════════════════════════════════════╝")
#print(f"Fecha de ejecución : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
#print(f"Archivo fuente     : {ruta}")
#print(f"Archivo existe     : {'✓ Sí' if ruta.exists() else '✗ No'}")

if not ruta.exists():
    raise FileNotFoundError(f"No se encontró el archivo fuente: {ruta.resolve()}")

# -----------------------------------------------------------------------------
# 2) Carga robusta del CSV SINCA
# -----------------------------------------------------------------------------

df = pd.read_csv(
    ruta,
    sep=";",
    decimal=",",
    encoding="latin-1"
)

filas_originales, columnas_originales = df.shape

# -----------------------------------------------------------------------------
# 3) Limpieza estructural básica
# -----------------------------------------------------------------------------

filas_vacias = int(df.isna().all(axis=1).sum())
df = df.dropna(how="all").copy()

# -----------------------------------------------------------------------------
# 4) Conversión robusta de fecha
# -----------------------------------------------------------------------------

if "fecha" not in df.columns:
    raise KeyError("La columna 'fecha' no existe en el dataset.")

estrategia_fecha = "pd.to_datetime(format='mixed', cache=True)"

try:
    df["fecha"] = pd.to_datetime(df["fecha"], format="mixed", cache=True)
except Exception as e:
    estrategia_fecha = "pd.to_datetime(errors='coerce')"
    print(f"⚠ Aviso: conversión automática de fecha falló ({e}). Aplicando plan alternativo.")
    df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")

fechas_invalidas = int(df["fecha"].isna().sum())
df["fecha"] = df["fecha"].dt.floor("h")

# -----------------------------------------------------------------------------
# 5) Diccionario semántico de variables y unidades
# -----------------------------------------------------------------------------

dicc_columnas = {
    "MP2.5": ["µg/m³", "cuantitativo"],
    "MP10": ["µg/m³", "cuantitativo"],
    "temperatura": ["°C", "cuantitativo"],
    "humedad": ["%", "cuantitativo"],
    "presion": ["hPa", "cuantitativo"],
    "viento": ["m/s", "cuantitativo"],
    "radiacion": ["W/m²", "cuantitativo"],
    "inversion_termica": ["", "cualitativo"],
    "dia_semana": ["", "cualitativo"],
    "es_finde": ["", "cualitativo"],
    "es_festivo": ["", "cualitativo"],
    "fecha": ["", "temporal"],
    "estacion": ["", "cualitativo"],
    "comuna": ["", "cualitativo"],
}

dicc_dias_semana = {
    0: "Lunes",
    1: "Martes",
    2: "Miércoles",
    3: "Jueves",
    4: "Viernes",
    5: "Sábado",
    6: "Domingo",
}

dicc_booleano = {
    0: "No",
    1: "Sí",
}

mapeos = {
    "dia_semana": dicc_dias_semana,
    "es_finde": dicc_booleano,
    "es_festivo": dicc_booleano,
    "inversion_termica": dicc_booleano,
}

# -----------------------------------------------------------------------------
# 6) Homologación de variables categóricas
# -----------------------------------------------------------------------------

columnas_mapeadas = []
columnas_no_encontradas_mapeo = []

for col, dicc in mapeos.items():
    if col in df.columns:
        valores_antes = df[col].dropna().nunique()
        df[col] = df[col].map(dicc).fillna(df[col])
        valores_despues = df[col].dropna().nunique()
        columnas_mapeadas.append(f"{col} ({valores_antes}→{valores_despues})")
    else:
        columnas_no_encontradas_mapeo.append(col)

# -----------------------------------------------------------------------------
# 7) Enriquecimiento de encabezados con unidades físicas
# -----------------------------------------------------------------------------

nuevos_encabezados = {
    col: f"{col} ({valores[0]})" if valores[0].strip() else col
    for col, valores in dicc_columnas.items()
    if col in df.columns
}

df.rename(columns=nuevos_encabezados, inplace=True)

# -----------------------------------------------------------------------------
# 8) Clasificación analítica de variables
# -----------------------------------------------------------------------------

variables_cuantitativas = [
    nuevos_encabezados.get(col, col)
    for col, valores in dicc_columnas.items()
    if valores[1] == "cuantitativo" and nuevos_encabezados.get(col, col) in df.columns
]

variables_cualitativas = [
    nuevos_encabezados.get(col, col)
    for col, valores in dicc_columnas.items()
    if valores[1] == "cualitativo" and nuevos_encabezados.get(col, col) in df.columns
]

variables_temporales = [
    nuevos_encabezados.get(col, col)
    for col, valores in dicc_columnas.items()
    if valores[1] == "temporal" and nuevos_encabezados.get(col, col) in df.columns
]

# -----------------------------------------------------------------------------
# 9) Controles de calidad inicial
# -----------------------------------------------------------------------------

duplicados = int(df.duplicated().sum())
nulos_totales = int(df.isna().sum().sum())

fecha_min = df["fecha"].min()
fecha_max = df["fecha"].max()

columnas_con_unidad = [
    col for col in df.columns
    if "(" in col and ")" in col
]

# Versión formateada solo para visualización
df_preview = df.copy()
df_preview["fecha"] = pd.to_datetime(df_preview["fecha"], errors="coerce").dt.strftime("%Y-%m-%d %I:%M %p")

# -----------------------------------------------------------------------------
# 10) Output ejecutivo, robusto y no truncable
# -----------------------------------------------------------------------------

from IPython.display import display, Markdown

resumen_html = f"""
<div style="
    width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#052e16,#064e3b,#065f46);
    color:#ecfdf5;
    padding:18px;
    border-left:6px solid #34d399;
    border-radius:10px;
    margin-top:16px;
    margin-bottom:16px;
">

<h3 style="margin-top:0;color:#ffffff;">
✅ Resultado de Carga y Normalización Inicial
</h3>

<table style="
    width:100%;
    border-collapse:collapse;
    font-size:14px;
    color:#ecfdf5;
">
<tr><td><strong>Archivo fuente</strong></td><td>{ruta.name}</td></tr>
<tr><td><strong>Filas originales</strong></td><td>{filas_originales:,}</td></tr>
<tr><td><strong>Columnas originales</strong></td><td>{columnas_originales:,}</td></tr>
<tr><td><strong>Filas vacías eliminadas</strong></td><td>{filas_vacias:,}</td></tr>
<tr><td><strong>Filas finales</strong></td><td>{df.shape[0]:,}</td></tr>
<tr><td><strong>Columnas finales</strong></td><td>{df.shape[1]:,}</td></tr>
<tr><td><strong>Fechas inválidas</strong></td><td>{fechas_invalidas:,}</td></tr>
<tr><td><strong>Registros duplicados</strong></td><td>{duplicados:,}</td></tr>
<tr><td><strong>Valores nulos totales</strong></td><td>{nulos_totales:,}</td></tr>
<tr><td><strong>Memoria utilizada</strong></td><td>{df.memory_usage(deep=True).sum() / 1024**2:.2f} MB</td></tr>
<tr><td><strong>Fecha mínima</strong></td><td>{fecha_min}</td></tr>
<tr><td><strong>Fecha máxima</strong></td><td>{fecha_max}</td></tr>
<tr><td><strong>Granularidad temporal</strong></td><td>Horaria</td></tr>
</table>

<p style="
    margin-top:14px;
    margin-bottom:0;
    font-size:14px;
    line-height:1.7;
">
<strong>Conclusión técnica:</strong> El dataset fue cargado correctamente, respetando el formato SINCA
(<strong>sep=';'</strong>, <strong>decimal=','</strong>, <strong>encoding='latin-1'</strong>).
La variable temporal fue normalizada a granularidad horaria y las variables fueron enriquecidas
con unidades físicas y clasificación analítica.
</p>

</div>
"""

display(Markdown(resumen_html))

# Vista controlada del dataset: evita truncamiento excesivo
columnas_preview = list(df_preview.columns[:8])

print("Vista preliminar controlada del dataset:")
print(f"Mostrando primeras 5 filas y {len(columnas_preview)} columnas de {df_preview.shape[1]} columnas totales.")

display(df_preview[columnas_preview].head(5))

<div style="
    width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#052e16,#064e3b,#065f46);
    color:#ecfdf5;
    padding:18px;
    border-left:6px solid #34d399;
    border-radius:10px;
    margin-top:16px;
    margin-bottom:16px;
">

<h3 style="margin-top:0;color:#ffffff;">
✅ Resultado de Carga y Normalización Inicial
</h3>

<table style="
    width:100%;
    border-collapse:collapse;
    font-size:14px;
    color:#ecfdf5;
">
<tr><td><strong>Archivo fuente</strong></td><td>sinca_santiago.csv</td></tr>
<tr><td><strong>Filas originales</strong></td><td>192,720</td></tr>
<tr><td><strong>Columnas originales</strong></td><td>14</td></tr>
<tr><td><strong>Filas vacías eliminadas</strong></td><td>0</td></tr>
<tr><td><strong>Filas finales</strong></td><td>192,720</td></tr>
<tr><td><strong>Columnas finales</strong></td><td>14</td></tr>
<tr><td><strong>Fechas inválidas</strong></td><td>0</td></tr>
<tr><td><strong>Registros duplicados</strong></td><td>0</td></tr>
<tr><td><strong>Valores nulos totales</strong></td><td>14,450</td></tr>
<tr><td><strong>Memoria utilizada</strong></td><td>75.80 MB</td></tr>
<tr><td><strong>Fecha mínima</strong></td><td>2022-01-01 00:00:00</td></tr>
<tr><td><strong>Fecha máxima</strong></td><td>2023-12-31 23:00:00</td></tr>
<tr><td><strong>Granularidad temporal</strong></td><td>Horaria</td></tr>
</table>

<p style="
    margin-top:14px;
    margin-bottom:0;
    font-size:14px;
    line-height:1.7;
">
<strong>Conclusión técnica:</strong> El dataset fue cargado correctamente, respetando el formato SINCA
(<strong>sep=';'</strong>, <strong>decimal=','</strong>, <strong>encoding='latin-1'</strong>).
La variable temporal fue normalizada a granularidad horaria y las variables fueron enriquecidas
con unidades físicas y clasificación analítica.
</p>

</div>

Vista preliminar controlada del dataset:
Mostrando primeras 5 filas y 8 columnas de 14 columnas totales.

,fecha,estacion,comuna,MP2.5 (µg/m³),MP10 (µg/m³),temperatura (°C),humedad (%),presion (hPa)
0,2022-01-01 12:00 AM,Pudahuel,Pudahuel,20.900,47.300,20.200,51.900,"1,016.900"
1,2022-01-01 01:00 AM,Pudahuel,Pudahuel,5.100,19.100,17.200,57.300,"1,019.400"
2,2022-01-01 02:00 AM,Pudahuel,Pudahuel,5.000,18.800,14.600,56.100,"1,016.300"
3,2022-01-01 03:00 AM,Pudahuel,Pudahuel,2.000,14.100,14.500,59.700,"1,014.500"
4,2022-01-01 04:00 AM,Pudahuel,Pudahuel,11.900,27.700,16.800,54.900,"1,020.600"

<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0f172a,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,30px);
    border-left:clamp(5px,0.8vw,7px) solid #f59e0b;
    border-radius:12px;
    box-shadow:0 8px 20px rgba(0,0,0,0.20);
    margin-bottom:24px;
    overflow-wrap:break-word;
    word-wrap:break-word;
">

<h2 style="
    margin-top:0;
    margin-bottom:16px;
    color:#ffffff;
    font-size:clamp(24px,3vw,32px);
    font-weight:700;
">
4. Inspección General y Calidad de los Datos
</h2>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#fef3c7;
    text-align:justify;
    margin-bottom:16px;
">
En esta etapa se realiza una revisión estructural y estadística del dataset ya cargado, con el propósito de evaluar su composición, tipos de variables, volumen de registros, valores faltantes, duplicados y comportamiento descriptivo inicial. Esta revisión permite establecer una línea base objetiva sobre la calidad de los datos antes de ejecutar procesos de limpieza, imputación o análisis exploratorio avanzado.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#78350f;
    border-left:5px solid #fbbf24;
    padding:clamp(14px,2vw,18px);
    border-radius:8px;
    margin-top:20px;
">

<h3 style="
    margin-top:0;
    margin-bottom:10px;
    color:#fde68a;
    font-size:clamp(16px,2vw,20px);
">
📊 Resultado Esperado
</h3>

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#ffffff;
    text-align:justify;
">
Obtener una visión ejecutiva y verificable del estado inicial del dataset, identificando dimensiones, tipos de datos, valores nulos, duplicados, memoria utilizada y estadísticas descriptivas relevantes sin generar salidas extensas o truncadas en el notebook.
</p>

</div>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:18px;
    padding:clamp(14px,2vw,18px);
    background:#451a03;
    border:1px solid #f59e0b;
    border-radius:8px;
">

<p style="
    margin:0;
    font-size:clamp(14px,1.4vw,15px);
    line-height:1.8;
    color:#fef3c7;
    text-align:justify;
">
📘 <strong>Justificación Técnica:</strong>
Se evita el uso directo de <code>df.info()</code> y salidas completas de <code>df.describe()</code>, ya que pueden generar resultados extensos y poco legibles. En su lugar, se construye un resumen ejecutivo controlado, reproducible y orientado a la evaluación de calidad de datos.
</p>

</div>

</div>

In [11]:
# =============================================================================
# 4. INSPECCIÓN GENERAL Y CALIDAD DE LOS DATOS
# =============================================================================

from IPython.display import display, Markdown

# -----------------------------------------------------------------------------
# Métricas estructurales principales
# -----------------------------------------------------------------------------

registros = df.shape[0]
variables = df.shape[1]
nulos_totales = int(df.isna().sum().sum())
duplicados = int(df.duplicated().sum())
memoria_mb = df.memory_usage(deep=True).sum() / 1024**2

columnas_con_nulos = int((df.isna().sum() > 0).sum())
porcentaje_nulos = (nulos_totales / (registros * variables)) * 100 if registros * variables > 0 else 0

# -----------------------------------------------------------------------------
# Resumen por tipos de datos
# -----------------------------------------------------------------------------

tipos_df = (
    df.dtypes
      .astype(str)
      .value_counts()
      .rename_axis("Tipo de dato")
      .reset_index(name="Cantidad de variables")
)

# -----------------------------------------------------------------------------
# Ranking controlado de columnas con mayor cantidad de nulos
# -----------------------------------------------------------------------------

nulos_por_columna = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

nulos_por_columna.columns = ["Variable", "Valores nulos"]
nulos_por_columna["% nulos"] = (
    nulos_por_columna["Valores nulos"] / registros * 100
).round(2)

nulos_top = nulos_por_columna[nulos_por_columna["Valores nulos"] > 0].head(10)

# -----------------------------------------------------------------------------
# Estadísticas descriptivas controladas para variables numéricas
# -----------------------------------------------------------------------------

df_numerico = df.select_dtypes(include="number")

if not df_numerico.empty:
    estadisticas = (
        df_numerico
        .describe()
        .T[["count", "mean", "std", "min", "50%", "max"]]
        .rename(columns={
            "count": "Registros válidos",
            "mean": "Media",
            "std": "Desv. Est.",
            "min": "Mínimo",
            "50%": "Mediana",
            "max": "Máximo"
        })
        .round(2)
        .head(12)
    )
else:
    estadisticas = pd.DataFrame()

# -----------------------------------------------------------------------------
# Output ejecutivo en HTML
# -----------------------------------------------------------------------------

resumen_calidad_html = f"""
<div style="
    width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#451a03,#78350f,#92400e);
    color:#fffbeb;
    padding:18px;
    border-left:6px solid #fbbf24;
    border-radius:10px;
    margin-top:16px;
    margin-bottom:16px;
">

<h3 style="margin-top:0;color:#ffffff;">
📊 Resumen Ejecutivo de Calidad de Datos
</h3>

<table style="
    width:100%;
    border-collapse:collapse;
    font-size:14px;
    color:#fffbeb;
">
<tr><td><strong>Registros</strong></td><td>{registros:,}</td></tr>
<tr><td><strong>Variables</strong></td><td>{variables:,}</td></tr>
<tr><td><strong>Valores nulos totales</strong></td><td>{nulos_totales:,}</td></tr>
<tr><td><strong>% global de nulos</strong></td><td>{porcentaje_nulos:.2f}%</td></tr>
<tr><td><strong>Columnas con nulos</strong></td><td>{columnas_con_nulos:,}</td></tr>
<tr><td><strong>Registros duplicados</strong></td><td>{duplicados:,}</td></tr>
<tr><td><strong>Memoria utilizada</strong></td><td>{memoria_mb:.2f} MB</td></tr>
</table>

<p style="
    margin-top:14px;
    margin-bottom:0;
    font-size:14px;
    line-height:1.7;
">
<strong>Conclusión técnica:</strong> Se generó una inspección controlada del dataset,
priorizando métricas estructurales, calidad de datos y estadísticas descriptivas resumidas,
evitando salidas extensas o truncadas en el notebook.
</p>

</div>
"""

display(Markdown(resumen_calidad_html))

print("Distribución de tipos de datos:")
display(tipos_df)

if not nulos_top.empty:
    print("Top 10 variables con mayor cantidad de valores nulos:")
    display(nulos_top)
else:
    print("✓ No se detectaron valores nulos en el dataset.")

if not estadisticas.empty:
    print("Estadísticas descriptivas controladas de variables numéricas:")
    display(estadisticas)
else:
    print("⚠ No se detectaron variables numéricas para describir.")

<div style="
    width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#451a03,#78350f,#92400e);
    color:#fffbeb;
    padding:18px;
    border-left:6px solid #fbbf24;
    border-radius:10px;
    margin-top:16px;
    margin-bottom:16px;
">

<h3 style="margin-top:0;color:#ffffff;">
📊 Resumen Ejecutivo de Calidad de Datos
</h3>

<table style="
    width:100%;
    border-collapse:collapse;
    font-size:14px;
    color:#fffbeb;
">
<tr><td><strong>Registros</strong></td><td>192,720</td></tr>
<tr><td><strong>Variables</strong></td><td>14</td></tr>
<tr><td><strong>Valores nulos totales</strong></td><td>14,450</td></tr>
<tr><td><strong>% global de nulos</strong></td><td>0.54%</td></tr>
<tr><td><strong>Columnas con nulos</strong></td><td>5</td></tr>
<tr><td><strong>Registros duplicados</strong></td><td>0</td></tr>
<tr><td><strong>Memoria utilizada</strong></td><td>75.80 MB</td></tr>
</table>

<p style="
    margin-top:14px;
    margin-bottom:0;
    font-size:14px;
    line-height:1.7;
">
<strong>Conclusión técnica:</strong> Se generó una inspección controlada del dataset,
priorizando métricas estructurales, calidad de datos y estadísticas descriptivas resumidas,
evitando salidas extensas o truncadas en el notebook.
</p>

</div>

Distribución de tipos de datos:

     Tipo de dato  Cantidad de variables
0         float64                      7
1          object                      6
2  datetime64[ns]                      1

Top 10 variables con mayor cantidad de valores nulos:

           Variable  Valores nulos  % nulos
0      MP10 (µg/m³)           2890    1.500
1     MP2.5 (µg/m³)           2890    1.500
2     presion (hPa)           2890    1.500
3  radiacion (W/m²)           2890    1.500
4       humedad (%)           2890    1.500

Estadísticas descriptivas controladas de variables numéricas:

,Registros válidos,Media,Desv. Est.,Mínimo,Mediana,Máximo
MP2.5 (µg/m³),"189,830.000",26.200,18.570,2.000,24.400,97.400
MP10 (µg/m³),"189,830.000",54.510,30.450,5.400,50.800,184.000
temperatura (°C),"192,720.000",14.000,7.770,-4.000,14.000,35.000
humedad (%),"189,830.000",62.170,9.680,21.400,62.200,100.000
presion (hPa),"189,830.000","1,013.000",4.120,996.600,"1,013.000","1,028.900"
viento (m/s),"192,720.000",3.100,1.580,0.200,2.900,15.800
radiacion (W/m²),"189,830.000",306.990,387.170,0.000,43.000,"1,417.000"

<div style="
    width:100%;
    max-width:100%;
    box-sizing:border-box;
    background:linear-gradient(135deg,#0f172a,#111827,#1e293b);
    color:#f8fafc;
    padding:clamp(20px,3vw,30px);
    border-left:clamp(5px,0.8vw,7px) solid #ef4444;
    border-radius:12px;
    box-shadow:0 8px 20px rgba(0,0,0,0.20);
    margin-bottom:24px;
">

<h2 style="
    margin-top:0;
    margin-bottom:16px;
    color:#ffffff;
    font-size:clamp(24px,3vw,32px);
    font-weight:700;
">
5. Limpieza y Preparación del Dataset
</h2>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#fecaca;
    text-align:justify;
">
Una vez completada la inspección inicial, se procede a la etapa de limpieza de datos, cuyo objetivo es mejorar la calidad analítica del conjunto de información eliminando registros incompletos, inconsistencias estructurales y posibles elementos que puedan introducir sesgos durante el análisis exploratorio o el modelamiento posterior.
</p>

<p style="
    font-size:clamp(14px,1.5vw,16px);
    line-height:1.9;
    color:#fecaca;
    text-align:justify;
">
La estrategia de limpieza aplicada se fundamenta en el análisis estadístico realizado previamente. Dado que las variables cuantitativas presentan distribuciones relativamente estables y los valores faltantes representan una proporción reducida respecto del volumen total de datos, se opta por una limpieza conservadora basada en la eliminación controlada de registros incompletos, preservando la consistencia del conjunto de datos sin introducir valores artificiales.
</p>

<div style="
    width:100%;
    box-sizing:border-box;
    background:#7f1d1d;
    border-left:5px solid #f87171;
    padding:18px;
    border-radius:8px;
    margin-top:18px;
">

<h3 style="
    margin-top:0;
    color:#fecaca;
">
🧹 Resultado Esperado
</h3>

<p style="
    margin:0;
    color:#ffffff;
    line-height:1.8;
">
Obtener un dataset limpio, consistente y preparado para análisis exploratorio avanzado, minimizando la presencia de registros incompletos y garantizando la calidad de los datos utilizados durante las siguientes etapas del proyecto.
</p>

</div>

<div style="
    width:100%;
    box-sizing:border-box;
    margin-top:18px;
    padding:18px;
    background:#450a0a;
    border:1px solid #ef4444;
    border-radius:8px;
">

<p style="
    margin:0;
    color:#fecaca;
    line-height:1.8;
">
📘 <strong>Justificación Técnica:</strong>
La limpieza controlada de registros incompletos permite reducir ruido estadístico, mejorar la consistencia de las métricas descriptivas y garantizar que las conclusiones obtenidas reflejen adecuadamente el comportamiento real de las variables ambientales analizadas.
</p>

</div>

</div>

In [12]:
# =============================================================================
# 5. LIMPIEZA Y PREPARACIÓN DEL DATASET
# =============================================================================

from IPython.display import display, Markdown

# -----------------------------------------------------------------------------
# Validación inicial
# -----------------------------------------------------------------------------

if "df" not in globals():
    raise NameError(
        "El DataFrame principal 'df' no existe. "
        "Ejecute primero la etapa de carga de datos."
    )

df_limpio = df.copy()

# -----------------------------------------------------------------------------
# Diagnóstico previo
# -----------------------------------------------------------------------------

registros_iniciales = df_limpio.shape[0]
variables_iniciales = df_limpio.shape[1]

nulos_iniciales = int(df_limpio.isna().sum().sum())
duplicados_iniciales = int(df_limpio.duplicated().sum())

# Ranking controlado de nulos
top_nulos = (
    df_limpio.isna()
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_nulos.columns = ["Variable", "Valores nulos"]
top_nulos = top_nulos[top_nulos["Valores nulos"] > 0].head(10)

# -----------------------------------------------------------------------------
# Limpieza controlada
# -----------------------------------------------------------------------------

df_limpio = (
    df_limpio
    .dropna()
    .reset_index(drop=True)
)

# -----------------------------------------------------------------------------
# Métricas posteriores
# -----------------------------------------------------------------------------

registros_finales = df_limpio.shape[0]

registros_eliminados = registros_iniciales - registros_finales

porcentaje_eliminado = (
    registros_eliminados / registros_iniciales * 100
    if registros_iniciales > 0
    else 0
)

nulos_finales = int(df_limpio.isna().sum().sum())
duplicados_finales = int(df_limpio.duplicated().sum())

# -----------------------------------------------------------------------------
# Resumen ejecutivo
# -----------------------------------------------------------------------------

html_resumen = f"""
<div style="
background:linear-gradient(135deg,#450a0a,#7f1d1d,#991b1b);
padding:18px;
border-left:6px solid #f87171;
border-radius:10px;
color:white;
">

<h3>🧹 Resultado de la Limpieza del Dataset</h3>

<table style="width:100%;color:white;border-collapse:collapse;">
<tr><td><strong>Registros iniciales</strong></td><td>{registros_iniciales:,}</td></tr>
<tr><td><strong>Registros finales</strong></td><td>{registros_finales:,}</td></tr>
<tr><td><strong>Registros eliminados</strong></td><td>{registros_eliminados:,}</td></tr>
<tr><td><strong>% eliminado</strong></td><td>{porcentaje_eliminado:.2f}%</td></tr>
<tr><td><strong>Nulos iniciales</strong></td><td>{nulos_iniciales:,}</td></tr>
<tr><td><strong>Nulos finales</strong></td><td>{nulos_finales:,}</td></tr>
<tr><td><strong>Duplicados iniciales</strong></td><td>{duplicados_iniciales:,}</td></tr>
<tr><td><strong>Duplicados finales</strong></td><td>{duplicados_finales:,}</td></tr>
</table>

<p style="margin-top:15px;">
<strong>Conclusión:</strong> El proceso de limpieza eliminó los registros incompletos
identificados durante la etapa de diagnóstico, obteniendo un conjunto de datos
consistente y preparado para análisis exploratorio y modelamiento posterior.
</p>

</div>
"""

display(Markdown(html_resumen))

# -----------------------------------------------------------------------------
# Evidencia de calidad
# -----------------------------------------------------------------------------

if not top_nulos.empty:
    print("Variables con mayor cantidad de valores faltantes antes de la limpieza:")
    display(top_nulos)

print("\nVista preliminar del dataset limpio:")
display(df_limpio.head())

# Actualización del dataset principal
df = df_limpio.copy()

<div style="
background:linear-gradient(135deg,#450a0a,#7f1d1d,#991b1b);
padding:18px;
border-left:6px solid #f87171;
border-radius:10px;
color:white;
">

<h3>🧹 Resultado de la Limpieza del Dataset</h3>

<table style="width:100%;color:white;border-collapse:collapse;">
<tr><td><strong>Registros iniciales</strong></td><td>192,720</td></tr>
<tr><td><strong>Registros finales</strong></td><td>178,709</td></tr>
<tr><td><strong>Registros eliminados</strong></td><td>14,011</td></tr>
<tr><td><strong>% eliminado</strong></td><td>7.27%</td></tr>
<tr><td><strong>Nulos iniciales</strong></td><td>14,450</td></tr>
<tr><td><strong>Nulos finales</strong></td><td>0</td></tr>
<tr><td><strong>Duplicados iniciales</strong></td><td>0</td></tr>
<tr><td><strong>Duplicados finales</strong></td><td>0</td></tr>
</table>

<p style="margin-top:15px;">
<strong>Conclusión:</strong> El proceso de limpieza eliminó los registros incompletos
identificados durante la etapa de diagnóstico, obteniendo un conjunto de datos
consistente y preparado para análisis exploratorio y modelamiento posterior.
</p>

</div>

Variables con mayor cantidad de valores faltantes antes de la limpieza:

           Variable  Valores nulos
0      MP10 (µg/m³)           2890
1     MP2.5 (µg/m³)           2890
2     presion (hPa)           2890
3  radiacion (W/m²)           2890
4       humedad (%)           2890

Vista preliminar del dataset limpio:

,fecha,estacion,comuna,MP2.5 (µg/m³),MP10 (µg/m³),temperatura (°C),humedad (%),presion (hPa),viento (m/s),radiacion (W/m²),inversion_termica,dia_semana,es_finde,es_festivo
0,2022-01-01 00:00:00,Pudahuel,Pudahuel,20.900,47.300,20.200,51.900,"1,016.900",1.900,35.000,Sí,Sábado,Sí,Sí
1,2022-01-01 01:00:00,Pudahuel,Pudahuel,5.100,19.100,17.200,57.300,"1,019.400",2.900,28.000,No,Sábado,Sí,Sí
2,2022-01-01 02:00:00,Pudahuel,Pudahuel,5.000,18.800,14.600,56.100,"1,016.300",2.700,52.000,No,Sábado,Sí,Sí
3,2022-01-01 03:00:00,Pudahuel,Pudahuel,2.000,14.100,14.500,59.700,"1,014.500",3.400,0.000,No,Sábado,Sí,Sí
4,2022-01-01 04:00:00,Pudahuel,Pudahuel,11.900,27.700,16.800,54.900,"1,020.600",0.900,2.000,No,Sábado,Sí,Sí

Se logra observar en la descripción que con la limpieza se tiene un dataset limpio.

In [ ]:
# ============================================================
# Limpieza robusta y exportación del dataset procesado
# Proyecto F3 - Calidad del Aire Santiago
# ============================================================

import os
import re
import unicodedata

# 1. Normalizar nombres de columnas
def normalizar_columna(col):
    col = str(col).strip()
    col = col.replace("µ", "u")
    col = unicodedata.normalize("NFKD", col)
    col = "".join(c for c in col if not unicodedata.combining(c))
    col = col.lower()
    col = re.sub(r"\s*\(.*?\)", "", col)
    col = col.replace(" ", "_")
    col = col.replace(".", "_")
    col = re.sub(r"_+", "_", col)
    return col.strip("_")

df.columns = [normalizar_columna(c) for c in df.columns]

print("Columnas normalizadas:")
print(df.columns.tolist())

# 2. Definir columnas clave existentes
columnas_clave = [
    "mp2_5",
    "mp10",
    "temperatura",
    "humedad",
    "presion",
    "viento",
    "radiacion"
]

columnas_existentes = [c for c in columnas_clave if c in df.columns]

if not columnas_existentes:
    raise ValueError(
        "No se encontraron columnas clave para limpieza. "
        f"Columnas disponibles: {df.columns.tolist()}"
    )

print(f"Columnas usadas para limpieza: {columnas_existentes}")

# 3. Eliminar registros incompletos solo en columnas relevantes
filas_antes = len(df)

df = (
    df
    .dropna(subset=columnas_existentes)
    .reset_index(drop=True)
)

filas_eliminadas = filas_antes - len(df)

print(f"Registros iniciales: {filas_antes:,}")
print(f"Registros eliminados: {filas_eliminadas:,}")
print(f"Registros finales: {len(df):,}")

# 4. Guardar dataset procesado
ruta_salida = "../data/processed/sinca_limpio.csv"

os.makedirs(os.path.dirname(ruta_salida), exist_ok=True)

df.to_csv(
    ruta_salida,
    index=False,
    encoding="utf-8"
)

print(f"Dataset limpio guardado correctamente en: {ruta_salida}")

---
## 6. Definici&oacute;n de episodio cr&iacute;tico

Existen 2 posibles episodios críticos: El primero es un MP2.5 promedio diario superior a 49 (µg/m³) y el segundo es un MP10 promedio diario superior a 179(µg/m³). Ambos umbrales son concentraciones necesarias para un aire regular. Con estos 2 episodios críticos se podrá definir condiciones meteorológicas y anticipar una alerta. La Normativa ambiental chilena exige que un promedio diario mínimo se calcule con 18Hr. Por lo tanto hay que eliminar filas asociadas a días con menos de 18 hrs muestreados

In [ ]:
# Convertir 'fecha' a datetime de forma robusta.
# Se intenta primero el formato explícito definido en la carga ('%Y-%m-%d %I:%M %p');
# si la columna ya viniera en otro tipo/formato, se hace un fallback silencioso.
# Esto evita el UserWarning de inferencia de formato de pandas.
if not pd.api.types.is_datetime64_any_dtype(df['fecha']):
    try:
        df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d %I:%M %p')
    except (ValueError, TypeError):
        df['fecha'] = pd.to_datetime(df['fecha'], format='mixed')

# Crear una columna temporal solo con la fecha (AAAA-MM-DD) para agrupar por día
df['solo_fecha'] = df['fecha'].dt.date

# Filtrar el DataFrame manteniendo solo los grupos que tienen 18 o más registros
df_filtrado = df.groupby(['solo_fecha', 'comuna']).filter(lambda x: len(x) >= 18)

# Eliminar la columna temporal si ya no la necesitas
df_filtrado = df_filtrado.drop(columns=['solo_fecha'])

# Verificar cuántos datos quedaron
print(f"Registros originales: {len(df)}")
print(f"Registros después del filtro: {len(df_filtrado)}")
df_filtrado.head()

In [ ]:
# ============================================================
# Cálculo de promedios diarios y detección de días críticos
# Proyecto F3 - Calidad del Aire Santiago
# ============================================================

import pandas as pd
import unicodedata
import re

# 1. Función para normalizar nombres de columnas
def normalizar_columna(col):
    col = str(col).strip()
    col = col.replace("µ", "u")
    col = unicodedata.normalize("NFKD", col)
    col = "".join(c for c in col if not unicodedata.combining(c))
    col = col.lower()
    col = re.sub(r"\s*\(.*?\)", "", col)
    col = col.replace(" ", "_")
    col = col.replace(".", "_")
    col = re.sub(r"_+", "_", col)
    return col.strip("_")

# 2. Trabajar sobre una copia segura
df_work = df_filtrado.copy()
df_work.columns = [normalizar_columna(c) for c in df_work.columns]

print("Columnas disponibles:")
print(df_work.columns.tolist())

# 3. Validar columnas obligatorias
columnas_requeridas = ["fecha", "comuna", "estacion", "mp2_5", "mp10"]

faltantes = [c for c in columnas_requeridas if c not in df_work.columns]

if faltantes:
    raise KeyError(
        f"Faltan columnas requeridas: {faltantes}. "
        f"Columnas disponibles: {df_work.columns.tolist()}"
    )

# 4. Asegurar formato de fecha
df_work["fecha"] = pd.to_datetime(
    df_work["fecha"],
    errors="coerce"
)

df_work = df_work.dropna(subset=["fecha"]).copy()
df_work["solo_fecha"] = df_work["fecha"].dt.date

# 5. Asegurar formato numérico en contaminantes
for col in ["mp2_5", "mp10"]:
    df_work[col] = pd.to_numeric(
        df_work[col],
        errors="coerce"
    )

# 6. Eliminar registros sin contaminantes principales
df_work = df_work.dropna(
    subset=["mp2_5", "mp10"]
).reset_index(drop=True)

# 7. Umbrales de referencia
UMBRAL25 = 49
UMBRAL10 = 179

# 8. Promedios diarios por fecha, comuna y estación
mp25_diario = (
    df_work
    .groupby(["solo_fecha", "comuna", "estacion"], as_index=False)
    .agg(mp2_5_promedio_diario=("mp2_5", "mean"))
)

mp10_diario = (
    df_work
    .groupby(["solo_fecha", "comuna", "estacion"], as_index=False)
    .agg(mp10_promedio_diario=("mp10", "mean"))
)

# 9. Identificación de días críticos
mp25_critico = (
    mp25_diario[mp25_diario["mp2_5_promedio_diario"] > UMBRAL25]
    .sort_values(by=["solo_fecha", "comuna", "estacion"])
    .reset_index(drop=True)
)

mp10_critico = (
    mp10_diario[mp10_diario["mp10_promedio_diario"] > UMBRAL10]
    .sort_values(by=["solo_fecha", "comuna", "estacion"])
    .reset_index(drop=True)
)

# 10. Resumen ejecutivo
print(f"\nTotal de combinaciones día/comuna/estación analizadas MP2.5: {len(mp25_diario):,}")
print(f"Total de combinaciones día/comuna/estación analizadas MP10: {len(mp10_diario):,}")
print(f"MP2.5 > {UMBRAL25} µg/m³: {len(mp25_critico):,} registros críticos")
print(f"MP10 > {UMBRAL10} µg/m³: {len(mp10_critico):,} registros críticos")

# 11. Vista rápida de resultados
display(mp25_critico.head(10))
display(mp10_critico.head(10))

Considerando que MP10 no tuvo ningún día, se analizará solo MP2.5.

In [ ]:
# ============================================================
# Detección de episodios críticos de MP2.5
# ============================================================

UMBRAL_MP25 = 50

# Validar existencia de la columna
if "mp2_5" not in df.columns:
    raise KeyError(
        f"No existe la columna 'mp2_5'. "
        f"Columnas disponibles: {df.columns.tolist()}"
    )

# Asegurar formato numérico
df["mp2_5"] = pd.to_numeric(
    df["mp2_5"],
    errors="coerce"
)

# Crear indicador de episodio crítico
df["critico_mp25"] = (
    df["mp2_5"] > UMBRAL_MP25
).astype(int)

# Métricas
total_registros = len(df)

total_criticos = int(
    df["critico_mp25"].sum()
)

pct_criticos = (
    total_criticos / total_registros * 100
    if total_registros > 0
    else 0
)

print("=" * 60)
print("ANÁLISIS DE EPISODIOS CRÍTICOS MP2.5")
print("=" * 60)
print(f"Umbral utilizado      : {UMBRAL_MP25} µg/m³")
print(f"Total registros       : {total_registros:,}")
print(f"Registros críticos    : {total_criticos:,}")
print(f"Porcentaje crítico    : {pct_criticos:.2f}%")
print("=" * 60)

---
## 7. Panel exploratorio

Se realizan gráficos para visualizar el comportamiento de la variable de estudio: Su eolución con respecto a las otras magitudes, su comportamiento frente a inversión térmica, fin de semanas y días festivos, su comportamiento diario y su comportamiento mensual.

In [ ]:
# ============================================================
# Relación MP2.5 versus variables meteorológicas
# ============================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Configuración de estilo global
sns.set_theme(style="whitegrid")

# Trabajar sobre copia segura
df_plot = df_filtrado.copy()

# Normalizar fecha
df_plot["fecha"] = pd.to_datetime(
    df_plot["fecha"],
    errors="coerce"
)

df_plot = df_plot.dropna(subset=["fecha"]).copy()
df_plot["año_mes"] = df_plot["fecha"].dt.to_period("M").astype(str)

# Definir variable objetivo y variables meteorológicas
variable_objetivo = "mp2_5"

variables_num = [
    "temperatura",
    "humedad",
    "presion",
    "viento",
    "radiacion"
]

# Validar columnas disponibles
columnas_necesarias = [variable_objetivo] + variables_num
columnas_faltantes = [
    c for c in columnas_necesarias
    if c not in df_plot.columns
]

if columnas_faltantes:
    raise KeyError(
        f"Faltan columnas para graficar: {columnas_faltantes}. "
        f"Columnas disponibles: {df_plot.columns.tolist()}"
    )

# Asegurar formato numérico
for col in columnas_necesarias:
    df_plot[col] = pd.to_numeric(
        df_plot[col],
        errors="coerce"
    )

df_plot = df_plot.dropna(
    subset=columnas_necesarias
).reset_index(drop=True)

# Gráficos
fig, axes = plt.subplots(
    1,
    len(variables_num),
    figsize=(22, 5)
)

for i, var in enumerate(variables_num):
    sns.scatterplot(
        data=df_plot,
        x=var,
        y=variable_objetivo,
        ax=axes[i],
        alpha=0.4,
        edgecolor=None
    )

    titulo_var = var.replace("_", " ").capitalize()
    axes[i].set_title(f"MP2.5 vs {titulo_var}")
    axes[i].set_xlabel(titulo_var)

    if i == 0:
        axes[i].set_ylabel("MP2.5")
    else:
        axes[i].set_ylabel("")

plt.suptitle(
    "Relación MP2.5 con variables meteorológicas",
    fontsize=16,
    fontweight="bold",
    y=1.05
)

plt.tight_layout()
plt.show()

### 7.x Construcción del DataFrame con variables booleanas

El DataFrame `mp25_diario` (promedio diario) se agrega por día, comuna y estación, por lo que las variables cualitativas booleanas (`inversion_termica`, `es_finde`, `es_festivo`) no se conservan en esa agregación. Aquí se reconstruye `mp25_diario_con_boolean` reincorporando dichas variables —que son constantes dentro de cada día/comuna/estación— tomando su primer valor por grupo. Esto permite analizar la distribución de MP2.5 según cada condición booleana.

In [ ]:
# ============================================================
# Reconstrucción del DataFrame diario con variables booleanas
# ============================================================

import pandas as pd

# Copia segura
df_bool = df_filtrado.copy()

# Crear solo_fecha desde fecha si no existe
if "solo_fecha" not in df_bool.columns:
    if "fecha" not in df_bool.columns:
        raise KeyError(
            f"No existe 'solo_fecha' ni 'fecha'. "
            f"Columnas disponibles: {df_bool.columns.tolist()}"
        )

    df_bool["fecha"] = pd.to_datetime(
        df_bool["fecha"],
        errors="coerce"
    )

    df_bool["solo_fecha"] = df_bool["fecha"].dt.date

# Variables booleanas esperadas
variables_bool = [
    "inversion_termica",
    "es_finde",
    "es_festivo"
]

# Booleanas presentes
bool_presentes = [
    c for c in variables_bool
    if c in df_bool.columns
]

faltantes_bool = [
    c for c in variables_bool
    if c not in df_bool.columns
]

if faltantes_bool:
    print(f"Aviso: columnas booleanas no encontradas: {faltantes_bool}")

# Validar columna objetivo
if "mp2_5" not in df_bool.columns:
    raise KeyError(
        f"No existe la columna 'mp2_5'. "
        f"Columnas disponibles: {df_bool.columns.tolist()}"
    )

# Validar columnas de agrupación
columnas_grupo = [
    "solo_fecha",
    "comuna",
    "estacion"
]

faltantes_grupo = [
    c for c in columnas_grupo
    if c not in df_bool.columns
]

if faltantes_grupo:
    raise KeyError(
        f"Faltan columnas de agrupación: {faltantes_grupo}. "
        f"Columnas disponibles: {df_bool.columns.tolist()}"
    )

# Asegurar MP2.5 numérico
df_bool["mp2_5"] = pd.to_numeric(
    df_bool["mp2_5"],
    errors="coerce"
)

# Normalizar booleanas Sí/No a 1/0 si existen
for col in bool_presentes:
    df_bool[col] = (
        df_bool[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .map({
            "sí": 1,
            "si": 1,
            "true": 1,
            "1": 1,
            "yes": 1,
            "no": 0,
            "false": 0,
            "0": 0
        })
    )

# Diccionario de agregación
agg_dict = {
    "mp2_5": "mean"
}

for c in bool_presentes:
    agg_dict[c] = "first"

# Construcción del DataFrame diario
mp25_diario_con_boolean = (
    df_bool
    .dropna(subset=["mp2_5", "solo_fecha", "comuna", "estacion"])
    .groupby(columnas_grupo, as_index=False)
    .agg(agg_dict)
    .rename(columns={
        "mp2_5": "mp2_5_promedio_diario"
    })
)

print(f"Filas en mp25_diario_con_boolean: {len(mp25_diario_con_boolean):,}")
print(f"Columnas: {list(mp25_diario_con_boolean.columns)}")

display(mp25_diario_con_boolean.head())

In [ ]:
# ============================================================
# Boxplot de MP2.5 según variables booleanas
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# Variables booleanas disponibles
cols_plot = [
    c for c in variables_bool
    if c in mp25_diario_con_boolean.columns
]

if len(cols_plot) == 0:
    raise ValueError(
        "No existen variables booleanas disponibles para graficar."
    )

# Validar columna objetivo
if "mp2_5_promedio_diario" not in mp25_diario_con_boolean.columns:
    raise KeyError(
        f"No existe 'mp2_5_promedio_diario'. "
        f"Columnas disponibles: {mp25_diario_con_boolean.columns.tolist()}"
    )

# Copia segura
df_box = mp25_diario_con_boolean.copy()

# Asegurar formato numérico de MP2.5
df_box["mp2_5_promedio_diario"] = pd.to_numeric(
    df_box["mp2_5_promedio_diario"],
    errors="coerce"
)

# Conversión robusta de booleanas
for var in cols_plot:

    print(f"\nValores encontrados en '{var}':")
    print(df_box[var].value_counts(dropna=False))

    df_box[var] = (
        df_box[var]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace({
            "sí": 1,
            "si": 1,
            "true": 1,
            "1": 1,
            "yes": 1,

            "no": 0,
            "false": 0,
            "0": 0
        })
    )

    df_box[var] = pd.to_numeric(
        df_box[var],
        errors="coerce"
    )

# Eliminar registros inválidos
df_box = df_box.dropna(
    subset=["mp2_5_promedio_diario"]
).reset_index(drop=True)

# Umbral normativo
UMBRAL25 = 49

# Crear figura
n = len(cols_plot)

fig, axes = plt.subplots(
    1,
    n,
    figsize=(6 * n, 5)
)

if n == 1:
    axes = [axes]

# Generar boxplots
for idx, var in enumerate(cols_plot):

    sns.boxplot(
        data=df_box,
        x=var,
        y="mp2_5_promedio_diario",
        hue=var,
        legend=False,
        ax=axes[idx],
        width=0.6
    )

    titulo = var.replace("_", " ").title()

    axes[idx].set_title(
        f"MP2.5 según {titulo}",
        fontsize=12,
        fontweight="bold"
    )

    axes[idx].set_xlabel(titulo)

    if idx == 0:
        axes[idx].set_ylabel("MP2.5 Promedio Diario")
    else:
        axes[idx].set_ylabel("")

    axes[idx].axhline(
        UMBRAL25,
        color="red",
        linestyle="--",
        linewidth=2,
        label=f"Umbral {UMBRAL25} µg/m³"
    )

    axes[idx].legend(
        loc="upper right",
        fontsize=9
    )

    axes[idx].grid(
        axis="y",
        alpha=0.3
    )

plt.suptitle(
    "Distribución de MP2.5 según Variables Booleanas",
    fontsize=14,
    fontweight="bold",
    y=1.02
)

plt.tight_layout()
plt.show()

In [ ]:
# ============================================================
# Gráfico de evolución temporal de MP2.5 por comuna
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

df_temporal = mp25_diario.copy()

# Validar columnas requeridas
columnas_requeridas = [
    "solo_fecha",
    "comuna",
    "mp2_5_promedio_diario"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in df_temporal.columns
]

if faltantes:
    raise KeyError(
        f"Faltan columnas requeridas: {faltantes}. "
        f"Columnas disponibles: {df_temporal.columns.tolist()}"
    )

# Asegurar formatos
df_temporal["solo_fecha"] = pd.to_datetime(
    df_temporal["solo_fecha"],
    errors="coerce"
)

df_temporal["mp2_5_promedio_diario"] = pd.to_numeric(
    df_temporal["mp2_5_promedio_diario"],
    errors="coerce"
)

df_temporal = df_temporal.dropna(
    subset=["solo_fecha", "comuna", "mp2_5_promedio_diario"]
)

# Configuración
UMBRAL25 = 49

fig, ax = plt.subplots(figsize=(14, 6))

# Graficar una línea por comuna
for comuna in sorted(df_temporal["comuna"].dropna().unique()):
    datos_comuna = (
        df_temporal[df_temporal["comuna"] == comuna]
        .sort_values("solo_fecha")
    )

    ax.plot(
        datos_comuna["solo_fecha"],
        datos_comuna["mp2_5_promedio_diario"],
        label=comuna,
        linewidth=1.5,
        alpha=0.8
    )

# Línea de umbral
ax.axhline(
    UMBRAL25,
    linestyle="--",
    linewidth=2,
    label=f"Umbral {UMBRAL25} µg/m³"
)

ax.set_xlabel("Fecha", fontsize=12, fontweight="bold")
ax.set_ylabel("MP2.5 Promedio Diario", fontsize=12, fontweight="bold")
ax.set_title(
    "Evolución temporal de MP2.5 por comuna",
    fontsize=14,
    fontweight="bold",
    pad=20
)

ax.grid(True, alpha=0.3)

ax.legend(
    loc="upper left",
    bbox_to_anchor=(1.02, 1),
    fontsize=9,
    ncol=1,
    framealpha=0.95
)

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# ============================================================
# Promedio mensual de MP2.5 por comuna
# ============================================================

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Copia segura
mp25_mensual_plot = df.copy()

# Validar columnas necesarias
columnas_requeridas = [
    "fecha",
    "comuna",
    "mp2_5"
]

faltantes = [
    c for c in columnas_requeridas
    if c not in mp25_mensual_plot.columns
]

if faltantes:
    raise KeyError(
        f"Faltan columnas requeridas: {faltantes}. "
        f"Columnas disponibles: {mp25_mensual_plot.columns.tolist()}"
    )

# Formatos correctos
mp25_mensual_plot["fecha"] = pd.to_datetime(
    mp25_mensual_plot["fecha"],
    errors="coerce"
)

mp25_mensual_plot["mp2_5"] = pd.to_numeric(
    mp25_mensual_plot["mp2_5"],
    errors="coerce"
)

mp25_mensual_plot = mp25_mensual_plot.dropna(
    subset=["fecha", "comuna", "mp2_5"]
)

# Crear mes
mp25_mensual_plot["mes"] = (
    mp25_mensual_plot["fecha"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

# Agrupar promedio mensual
mp25_mensual_plot = (
    mp25_mensual_plot
    .groupby(["comuna", "mes"], as_index=False)
    .agg(mp2_5_promedio_mensual=("mp2_5", "mean"))
    .sort_values(["comuna", "mes"])
)

# Gráfico
UMBRAL25 = 49

fig, ax = plt.subplots(figsize=(14, 8))

sns.lineplot(
    data=mp25_mensual_plot,
    x="mes",
    y="mp2_5_promedio_mensual",
    hue="comuna",
    marker="o",
    linewidth=1.5,
    ax=ax,
    palette="tab10"
)

ax.axhline(
    UMBRAL25,
    linestyle="--",
    linewidth=1.8,
    label=f"Umbral {UMBRAL25} µg/m³"
)

ax.set_title(
    "Promedio mensual de MP2.5 por comuna",
    fontsize=15,
    fontweight="bold"
)

ax.set_xlabel("Mes", fontsize=12)
ax.set_ylabel("MP2.5 promedio mensual", fontsize=12)

ax.xaxis.set_major_formatter(
    mdates.DateFormatter("%Y-%m")
)

ax.tick_params(axis="x", rotation=45)

ax.legend(
    title="Comuna",
    bbox_to_anchor=(1.02, 1),
    loc="upper left",
    frameon=True
)

plt.tight_layout()
plt.show()

In [ ]:
# ============================================================
# Calidad del aire en Santiago - Panel exploratorio
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

df_panel = df.copy()

# Validar columnas base
columnas_base = [
    "fecha",
    "comuna",
    "mp2_5",
    "viento",
    "temperatura"
]

faltantes = [c for c in columnas_base if c not in df_panel.columns]

if faltantes:
    raise KeyError(
        f"Faltan columnas base: {faltantes}. "
        f"Columnas disponibles: {df_panel.columns.tolist()}"
    )

# Crear hora y mes desde fecha
df_panel["fecha"] = pd.to_datetime(df_panel["fecha"], errors="coerce")
df_panel["hora"] = df_panel["fecha"].dt.hour
df_panel["mes"] = df_panel["fecha"].dt.month

# Asegurar numéricos
for col in ["mp2_5", "viento", "temperatura", "hora", "mes"]:
    df_panel[col] = pd.to_numeric(df_panel[col], errors="coerce")

df_panel = df_panel.dropna(
    subset=["fecha", "comuna", "mp2_5", "viento", "temperatura", "hora", "mes"]
).reset_index(drop=True)

UMBRAL = 50

fig, axes = plt.subplots(2, 2, figsize=(15, 10))

fig.suptitle(
    "Calidad del aire en Santiago - Panel exploratorio",
    fontsize=17,
    fontweight="bold",
    y=0.98
)

# 1. Ciclo horario
ax = axes[0, 0]
ch = df_panel.groupby("hora")["mp2_5"].mean().sort_index()

ax.plot(ch.index, ch.values, linewidth=2.5, marker="o", markersize=4)
ax.fill_between(ch.index, ch.values, alpha=0.15)
ax.axhline(UMBRAL, linestyle="--", linewidth=1.5, alpha=0.7, label=f"Umbral crítico ({UMBRAL})")
ax.set_title("Ciclo horario de MP2.5")
ax.set_xlabel("Hora del día")
ax.set_ylabel("MP2.5")
ax.legend()

# 2. Ranking por comuna
ax = axes[0, 1]
rank = df_panel.groupby("comuna")["mp2_5"].mean().sort_values()

ax.barh(rank.index, rank.values)
ax.set_title("MP2.5 promedio por comuna")
ax.set_xlabel("MP2.5")

# 3. Viento vs MP2.5
ax = axes[1, 0]
s = df_panel.sample(min(4000, len(df_panel)), random_state=1)

sc = ax.scatter(
    s["viento"],
    s["mp2_5"],
    c=s["temperatura"],
    cmap="coolwarm",
    alpha=0.5,
    s=14,
    edgecolors="none"
)

ax.set_title("Viento vs MP2.5")
ax.set_xlabel("Viento")
ax.set_ylabel("MP2.5")

cb = plt.colorbar(sc, ax=ax)
cb.set_label("Temperatura")

# 4. Estacionalidad
ax = axes[1, 1]
mm = df_panel.groupby("mes")["mp2_5"].mean().sort_index()

ax.bar(mm.index, mm.values)
ax.set_title("Estacionalidad mensual MP2.5")
ax.set_xlabel("Mes")
ax.set_ylabel("MP2.5")
ax.set_xticks(range(1, 13))

plt.tight_layout()
plt.show()

---
## 8. Correlaci&oacute;n entre variables

Mapa de calor que cuantifica la relaci&oacute;n lineal entre el MP2.5 y cada variable meteorol&oacute;gica.

In [ ]:
# ============================================================
# Correlación entre MP2.5 y variables meteorológicas
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# Variables normalizadas
vars_corr = [
    "mp2_5",
    "temperatura",
    "humedad",
    "presion",
    "viento",
    "radiacion"
]

# Validar columnas existentes
vars_corr = [c for c in vars_corr if c in df.columns]

if "mp2_5" not in vars_corr:
    raise KeyError(
        f"No existe la columna 'mp2_5'. "
        f"Columnas disponibles: {df.columns.tolist()}"
    )

if len(vars_corr) < 2:
    raise ValueError(
        f"No hay suficientes variables para calcular correlación. "
        f"Variables disponibles: {vars_corr}"
    )

# Copia segura y conversión numérica
df_corr = df[vars_corr].copy()

for col in vars_corr:
    df_corr[col] = pd.to_numeric(
        df_corr[col],
        errors="coerce"
    )

df_corr = df_corr.dropna()

# Calcular correlación
corr = df_corr.corr()

# Graficar matriz de correlación
fig, ax = plt.subplots(figsize=(9, 7))

im = ax.imshow(
    corr.values,
    cmap="RdBu_r",
    vmin=-1,
    vmax=1,
    aspect="auto"
)

ax.set_xticks(range(len(vars_corr)))
ax.set_yticks(range(len(vars_corr)))

ax.set_xticklabels(
    vars_corr,
    rotation=45,
    ha="right"
)

ax.set_yticklabels(vars_corr)

# Anotar valores
for i in range(len(vars_corr)):
    for j in range(len(vars_corr)):
        valor = corr.values[i, j]

        ax.text(
            j,
            i,
            f"{valor:.2f}",
            ha="center",
            va="center",
            color="white" if abs(valor) > 0.4 else "black",
            fontsize=9
        )

cb = fig.colorbar(im, ax=ax, shrink=0.8)
cb.set_label("Coeficiente de correlación")

ax.set_title(
    "Matriz de correlación",
    pad=14,
    fontweight="bold"
)

ax.grid(False)

plt.tight_layout()
plt.show()

Del mapa de calor se observa que las correlaciones entre M2.5 y el resto de magnitudes físicas son débiles.

---
## 9. Condiciones que anticipan un episodio cr&iacute;tico

El análisis exploratorio realizado sobre el conjunto de datos de calidad del aire de la Región Metropolitana permitió identificar patrones relevantes asociados al comportamiento del material particulado fino (MP2.5). Sin embargo, los resultados obtenidos indican que las variables meteorológicas analizadas de manera individual presentan correlaciones lineales débiles o moderadas respecto de las concentraciones de MP2.5.

Este resultado sugiere que los episodios críticos de contaminación atmosférica no dependen de una única variable ambiental, sino de la interacción simultánea de múltiples factores, entre ellos condiciones meteorológicas, actividad urbana, emisiones vehiculares, procesos industriales, calefacción residencial y fenómenos atmosféricos locales.

A partir de las visualizaciones generadas se observan además patrones estacionales relevantes. Durante los meses de otoño e invierno se aprecia un aumento sostenido en los niveles promedio de MP2.5, comportamiento consistente con la evidencia reportada para la cuenca de Santiago, donde las condiciones de estabilidad atmosférica y ventilación reducida favorecen la acumulación de contaminantes.

Por otra parte, el análisis de variables categóricas asociadas a días festivos, fines de semana e inversión térmica evidencia diferencias en la distribución de las concentraciones de MP2.5, aunque los resultados observados no permiten establecer reglas determinísticas que anticipen por sí solas la ocurrencia de episodios críticos.

En consecuencia, los hallazgos obtenidos permiten concluir que la predicción de eventos de contaminación requiere modelos multivariados capaces de integrar simultáneamente variables meteorológicas, temporales y territoriales, constituyendo una línea de trabajo relevante para futuras etapas del proyecto.

---
## 10. Conclusiones preliminares

El presente análisis permitió desarrollar una exploración integral del conjunto de datos de calidad del aire de Santiago, aplicando procesos de limpieza, validación, transformación y visualización orientados a garantizar la calidad y consistencia de la información utilizada.

Los resultados obtenidos muestran que las concentraciones de MP2.5 presentan una dinámica compleja y multifactorial. Si bien las variables meteorológicas analizadas aportan información relevante para comprender el fenómeno, ninguna de ellas explica por sí sola las variaciones observadas en los niveles de contaminación atmosférica.

El análisis temporal evidenció patrones estacionales claros, observándose mayores concentraciones promedio de material particulado durante los meses de invierno. Este comportamiento resulta consistente con fenómenos ampliamente documentados en la Región Metropolitana, asociados a condiciones de menor ventilación atmosférica, inversión térmica y aumento de emisiones derivadas de actividades residenciales y urbanas.

Asimismo, el análisis por comuna permitió identificar diferencias territoriales significativas en los niveles promedio de contaminación, lo que sugiere la existencia de factores locales asociados a densidad poblacional, movilidad urbana, actividad económica y características geográficas específicas de cada zona.

Las matrices de correlación y visualizaciones exploratorias muestran que las relaciones entre MP2.5 y las variables meteorológicas son, en términos generales, débiles o moderadas, reforzando la hipótesis de que la contaminación atmosférica responde a la interacción simultánea de múltiples factores ambientales y antropogénicos.

Desde una perspectiva metodológica, el trabajo desarrollado permitió construir una base de datos limpia, estructurada y reproducible, apta para etapas posteriores de análisis avanzado, modelamiento predictivo y aplicaciones de Machine Learning.

Como trabajo futuro, se recomienda incorporar técnicas de modelado supervisado, análisis multivariado y series temporales con el objetivo de identificar patrones complejos, estimar concentraciones futuras de contaminantes y apoyar procesos de monitoreo y toma de decisiones relacionados con la gestión de la calidad del aire en la Región Metropolitana de Santiago.

Esta versión está mucho más alineada con lo que espera un profesor de Magíster: se basa en evidencia observada, evita afirmaciones absolutas, conecta con los análisis que realizaste (correlación, temporalidad, comunas, variables meteorológicas) y deja una transición natural hacia futuras fases de Machine Learning. Además, es consistente con el nivel técnico que ya has incorporado en F3.